### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by earthxx** [WangRongsheng/MedQA-ChatGLM#1]
I want to use local data to fine-tune the mode by using ChatGLM , like this , how to works?

**Comment by WangRongsheng** [comment]
Yes,

1. `git clone https://github.com/WangRongsheng/MedQA-ChatGLM.git`
2. Install packages: `pip install -r requirements.txt`
3. Prepare data, Please reference data format: [data/self_cognition.json](https://github.com/WangRongsheng/MedQA-ChatGLM/blob/main/data/self_cognition.json)
4. Add your data path: [data/dataset_info.json](https://github.com/WangRongsheng/MedQA-ChatGLM/blob/main/data/dataset_info.json#L5)
5. Fine-tuning your model: 
```python
CUDA_VISIBLE_DEVICES=0 python MedQA-ChatGLM/finetune.py \
                              --do_train \
                              --dataset self_cognition \
                              --finetuning_type lora \
                              --output_dir ./fintuning-output-lora \
                              --per_device_train_batch_size 32 \
                              --gradient_accumulation_steps 256 \
                              --lr_scheduler_type cosine \
                              --logging_steps 500 \
                              --save_steps 1000 \
                              --learning_rate 5e-5 \
                              --num_train_epochs 10.0 \
                              --fp16
```

**Comment by earthxx** [comment]
yeah，but there are still some issues and I am very interested in your achievements, Can you leave me a contact information? For example, WeChat or email, etc？

**Comment by WangRongsheng** [comment]
yes, email: wrs6@88.com
