### ISSUE TITLE
训练阶段没有做验证

### ISSUE THREAD

**Issue by zhengorange** [WangRongsheng/MedQA-ChatGLM#9]
你好，阅读代码后发现，在训练阶段好像是没有配置相关的验证集计算loss阶段，这样会造成在训练集上过拟合吗？难道是因为大模型一般不会过拟合，所以验证的意义不大吗？

**Comment by WangRongsheng** [comment]
数据集较少时，设置epoch为5-10；数据集较大时，设置epoch为2-3即可；

这里没有加验证是因为没有写，并不是没有意义。

**Comment by zhengorange** [comment]
明白了，谢谢你。
